//

export const carModelsEndPoint = [
    { id: 1, modelName: "Urban Gruiser", modelImageUrl: require('../../../../assets/images/Cars/urbanGruiser.png') },
    { id: 2, modelName: "Camry", modelImageUrl: require('../../../../assets/images/Cars/camry.png') },
    { id: 3, modelName: "Corrola Axio", modelImageUrl: require('../../../../assets/images/Cars/CorrolaAxio.png') },
    { id: 4, modelName: "Etios", modelImageUrl: require('../../../../assets/images/Cars/Etios.png') },
    { id: 5, modelName: "Etios Cross", modelImageUrl: require('../../../../assets/images/Cars/etiosCross.png') },
    { id: 6, modelName: "Etios Live", modelImageUrl: require('../../../../assets/images/Cars/etiosLive.png') },
    { id: 7, modelName: "Fortuner", modelImageUrl: require('../../../../assets/images/Cars/fortuner.png') },
    { id: 8, modelName: "Glanza", modelImageUrl: require('../../../../assets/images/Cars/Glanza.png') },
    { id: 9, modelName: "Innova", modelImageUrl: require('../../../../assets/images/Cars/innova.png') },
    { id: 10, modelName: "Land Gruiser", modelImageUrl: require('../../../../assets/images/Cars/landGruiser.png') },
    { id: 11, modelName: "Corrola Altis", modelImageUrl: require('../../../../assets/images/Cars/CorrolaAltis.png') },
    { id: 12, modelName: "Qualiz", modelImageUrl: require('../../../../assets/images/Cars/qualiz.png') },
]

export const modalMonufactoringYearEndPoint = [
    { id: 1, year: "1998" },
    { id: 2, year: "1999" },
    { id: 3, year: "2000" },
    { id: 4, year: "2001" },
    { id: 5, year: "2002" },
    { id: 6, year: "2003" },
    { id: 7, year: "2004" },
    { id: 8, year: "2005" },
    { id: 9, year: "2006" },
    { id: 10, year: "2007" },
    { id: 11, year: "2008" },
    { id: 12, year: "2009" },
    { id: 13, year: "2010" },
    { id: 14, year: "2011" },
    { id: 15, year: "2012" },
    { id: 16, year: "2013" },
    { id: 17, year: "2014" },
    { id: 18, year: "2015" },
    { id: 19, year: "2016" },
    { id: 20, year: "2017" },
    { id: 21, year: "2018" },
    { id: 22, year: "2019" },
    { id: 23, year: "2020" },
    { id: 24, year: "2021" },
    { id: 25, year: "2022" },
    { id: 26, year: "2023" },
]